### ISSUE TITLE
Unable to boot instance from TheSparkBox image

### ISSUE THREAD

**Issue by fwerpers** [SNICScienceCloud/LDSA-Spark#1]
Initially I tried setting up the environment locally with Docker, which seemed to work until I experienced [this](https://github.com/docker/for-mac/issues/371 ).

Now I'm trying to do the setup on the SNIC cloud instead, but I'm unable to create an instance using the TheSparkBox image. This is the error message I get:

> Error: Failed to perform requested operation on instance "spark_instance", the instance has an error status: Please try again later [Error: Build of instance 5f1175a7-803e-4161-b345-c6b1f62afd41 aborted: Block Device Mapping is Invalid.].

**Comment by mcapuccini** [comment]
Hi @fwerpers. I am not commenting on the first issue, as it is still open in Docker. However, a few other students experienced your same problem on the SNIC cloud, and I think I can help there. When I saw this error before, it was enough to start the instance from the images menu' clicking on launch, instead of starting a new instance and then selecting the image. Please try this, and let me know how it goes.

**Comment by fwerpers** [comment]
Yep, that worked. The difference when starting an instance from the images menu seems to be that the "Create New Volume" option is set to "No". When starting it from the instances menu it is set to "Yes", which seems to have caused the error.

Thanks! 👍

**Comment by mcapuccini** [comment]
Good, thanks for sorting this out!

**Comment by ahellander** [comment]
But it is strange that it does not work to boot instances backed by volumes. 
Mvh
Andreas

————————————————————————
Andreas Hellander
Associate Professor in Scientific Computing
Project Leader SNIC Science Cloud
Department of Information Technology, Uppsala University
andreas.hellander@it.uu.se

**Comment by mcapuccini** [comment]
yeah... we should probably write to support
